### PR TITLE
Make public path configurable via an environment variable

### PR DESCRIPTION
**Pull request by jeromefroe**
Hi Temporal team! This PR addresses #179 by making the root path that the app is served under configurable via the `TEMPORAL_WEB_ROOT_PATH` environment variable. This approach is based on the [webpack documentation for the `publicPath` configuration option](https://webpack.js.org/guides/public-path/#environment-based). Thanks!

upd:
image

### CODE REVIEW

**Comment by sw-yx** [comment]
@feedmeapples should be a straightforward one hopefully - can you test and merge?

@jeromefroe for your usecase, have you verified that our `/api/` and `/auth/` routes dont need to be namespaced as well?

**Comment by jeromefroe** [comment]
@sw-yx this PR is going to need more work. I've done more testing and it looks like the Vue client needs to be updated as well to use the appropriate root path. I've tried updating [the `base` configuration option of the Vue Router](https://router.vuejs.org/api/#base) but it looks like more changes are still needed.

**Comment by sw-yx** [comment]
just checking in - hows it going?

**Comment by jeromefroe** [comment]
> just checking in - hows it going?

Hey @sw-yx! I think this PR is getting close, I've updated both the server-side and client-side to support being deployed under a subpath, but I've noticed that links will occasionally be redirected to URL's which duplicate the subpath. For example, if the subpath is `/temporal` then although the link will be to `/temporal/api/foo` it will get redirected to `/temporal/temporal/api/foo` which will result in a 404. Any pointers would be much appreciated since I'm not very familiar with Vue :)

**Comment by sw-yx** [comment]
this *might* be a base Url issue. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

 @feedmeapples any idea?

**Comment by feedmeapples** [comment]
looking into it to help and make it work

**Comment by garbage-collector** [comment]
any news on this pull request ? definitely waiting for it to have a proper temporal dashboard on my prod environment. Thanks !

**Comment by sw-yx** [comment]
no updates yet - i dont mind this in principle, just want to make sure @feedmeapples is fine with the code as he's responsible for maintaining going fwd

**Comment by feedmeapples** [comment]
> no updates yet - i dont mind this in principle, just want to make sure @feedmeapples is fine with the code as he's responsible for maintaining going fwd

i need to do something with the links, in the current state they end up duplicating the subpath and breaking the app. Looking into this again rn

**Review by feedmeapples — APPROVED** [review]

**Comment by feedmeapples** [comment]
Found what was causing subpath duplication in duplication

There was a code in App.vue -> globalClick that was overriding the handling of a link click. This code was messing the vue-router basePath behavior and adding additional subpath everytime links are clicked

Removing this code also happens to fix `ctrl+click` not opening links in a new tab. Now `ctrl+click` properly opens links in new tabs

**Comment by feedmeapples** [comment]
This should be good to check in with one more approve 👍

**Review by sw-yx — APPROVED** [review]

**Comment by feedmeapples** [comment]
@jeromefroe this feature seems had an issue in production build. I've merged changes to address this https://github.com/temporalio/web/pull/339

**Pull request merged**
